-- Paystack/Supabase schema for wedding contributions.
-- Run this whole file on a fresh Supabase project before starting the API.

CREATE TABLE IF NOT EXISTS gift_categories (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT,
  target_amount_minor BIGINT,
  currency TEXT NOT NULL DEFAULT 'NGN' CHECK (currency IN ('NGN')),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contributions (
  id UUID PRIMARY KEY,
  reference TEXT NOT NULL UNIQUE,
  category_id TEXT NOT NULL REFERENCES gift_categories(id),
  amount_minor BIGINT NOT NULL CHECK (amount_minor >= 50000),
  currency TEXT NOT NULL CHECK (currency IN ('NGN')),
  supporter_name TEXT NOT NULL CHECK (char_length(supporter_name) BETWEEN 1 AND 120),
  supporter_email TEXT NOT NULL CHECK (char_length(supporter_email) BETWEEN 3 AND 320),
  supporter_phone TEXT,
  supporter_message TEXT,
  is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  payment_provider TEXT,
  provider_reference TEXT,
  provider_access_code TEXT,
  checkout_url TEXT,
  payment_status TEXT NOT NULL DEFAULT 'CREATED'
    CHECK (payment_status IN ('CREATED','PENDING','PROCESSING','SUCCESSFUL','FAILED','CANCELLED','REFUNDED')),
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE contributions ADD COLUMN IF NOT EXISTS provider_access_code TEXT;
ALTER TABLE contributions ADD COLUMN IF NOT EXISTS checkout_url TEXT;
ALTER TABLE contributions ADD COLUMN IF NOT EXISTS initialization_started_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS contributions_provider_reference_uq
  ON contributions(payment_provider, provider_reference)
  WHERE provider_reference IS NOT NULL;

CREATE INDEX IF NOT EXISTS contributions_status_idx
  ON contributions(payment_status);

CREATE INDEX IF NOT EXISTS contributions_category_idx
  ON contributions(category_id);

CREATE TABLE IF NOT EXISTS payment_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL,
  event_type TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  reference TEXT NOT NULL,
  payload JSONB NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL,
  processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(provider, idempotency_key)
);

CREATE INDEX IF NOT EXISTS payment_events_reference_idx
  ON payment_events(reference);

CREATE OR REPLACE FUNCTION claim_payment_initialization(p_reference TEXT)
RETURNS contributions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE c contributions%ROWTYPE;
BEGIN
  SELECT * INTO c FROM contributions WHERE reference = p_reference FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Contribution not found for reference %', p_reference; END IF;
  IF c.payment_status = 'SUCCESSFUL' THEN RETURN c; END IF;
  IF c.payment_status = 'PENDING' AND c.checkout_url IS NOT NULL THEN RETURN c; END IF;
  IF c.payment_status = 'PROCESSING' AND c.initialization_started_at IS NOT NULL AND c.initialization_started_at > NOW() - INTERVAL '5 minutes' THEN
    RETURN c;
  END IF;
  UPDATE contributions SET payment_status='PROCESSING', initialization_started_at=NOW(), updated_at=NOW() WHERE reference=p_reference RETURNING * INTO c;
  RETURN c;
END;
$$;

REVOKE ALL ON FUNCTION claim_payment_initialization(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION claim_payment_initialization(TEXT) TO service_role;

CREATE OR REPLACE FUNCTION process_payment_event(
  p_provider TEXT,
  p_event_type TEXT,
  p_idempotency_key TEXT,
  p_reference TEXT,
  p_provider_reference TEXT,
  p_status TEXT,
  p_amount_minor BIGINT,
  p_currency TEXT,
  p_occurred_at TIMESTAMPTZ,
  p_payload JSONB
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  contribution contributions%ROWTYPE;
  inserted_event_id BIGINT;
BEGIN
  SELECT * INTO contribution
  FROM contributions
  WHERE reference = p_reference
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Contribution not found for reference %', p_reference;
  END IF;

  IF contribution.amount_minor <> p_amount_minor OR contribution.currency <> p_currency THEN
    RAISE EXCEPTION 'Payment amount or currency mismatch for reference %', p_reference;
  END IF;

  IF contribution.provider_reference IS NOT NULL AND contribution.provider_reference <> p_provider_reference THEN
    RAISE EXCEPTION 'Payment provider reference mismatch for reference %', p_reference;
  END IF;

  INSERT INTO payment_events(provider, event_type, idempotency_key, reference, payload, occurred_at)
  VALUES (p_provider, p_event_type, p_idempotency_key, p_reference, p_payload, p_occurred_at)
  ON CONFLICT (provider, idempotency_key) DO NOTHING
  RETURNING id INTO inserted_event_id;

  IF inserted_event_id IS NULL THEN
    RETURN;
  END IF;

  IF p_status = 'SUCCESSFUL' AND contribution.payment_status <> 'SUCCESSFUL' THEN
    UPDATE contributions
    SET payment_provider = p_provider,
        provider_reference = p_provider_reference,
        payment_status = 'SUCCESSFUL',
        initialization_started_at = NULL,
        paid_at = COALESCE(paid_at, p_occurred_at),
        updated_at = NOW()
    WHERE reference = p_reference;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION process_payment_event(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BIGINT, TEXT, TIMESTAMPTZ, JSONB) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION process_payment_event(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BIGINT, TEXT, TIMESTAMPTZ, JSONB) TO service_role;

INSERT INTO gift_categories (id, title, description, image_url, target_amount_minor, currency)
VALUES
  ('celebration', 'The Celebration', 'Help us bring the wedding day itself to life — flowers, music, and the little details that make it unforgettable.', 'https://picsum.photos/seed/jossyandrew-gift-celebration/900/700', 30000000, 'NGN'),
  ('honeymoon', 'The Honeymoon', 'Our first trip as a married couple — every gift here goes straight toward the adventure.', 'https://picsum.photos/seed/jossyandrew-gift-honeymoon/900/700', 50000000, 'NGN'),
  ('new-home', 'Our New Home', 'Setting up the place we''ll build our life together, one room at a time.', 'https://picsum.photos/seed/jossyandrew-gift-home/900/700', 40000000, 'NGN'),
  ('blessing', 'A General Blessing', 'No specific goal — just a gift from your heart to celebrate our new chapter, however you''d like to bless it.', 'https://picsum.photos/seed/jossyandrew-gift-blessing/900/700', NULL, 'NGN')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  image_url = EXCLUDED.image_url,
  target_amount_minor = EXCLUDED.target_amount_minor,
  currency = EXCLUDED.currency,
  updated_at = NOW();
